### ISSUE TITLE
TSLib - Fetch is not defined

### ISSUE THREAD

**Issue by franciscarriere** [commercelayer/commercelayer-js-auth#46]
**Describe the bug**
Brand new blank project.
NodeJS v16.20.0

Attempting to authenticate for a Integration (Client credential). 

Package JSON contents: 
```
 "devDependencies": {
      "@types/node": "^16.11.10",
      "ts-node": "10.7.0",
      "typescript": "4.5.2"
   },
   "dependencies": {
      "@commercelayer/js-auth": "^4.1.1",
      "@commercelayer/sdk": "^5.4.1",
      "mysql": "^2.14.1",
      "reflect-metadata": "^0.1.13",
      "typeorm": "0.3.16"
   },
```

Error: 

> /<projectPath>/node_modules/tslib/tslib.js:163
>         return new (P || (P = Promise))(function (resolve, reject) {
>                ^
> ReferenceError: fetch is not defined
>     at /<projectPath>/node_modules/@commercelayer/js-auth/lib/cjs/index.js:1:635
>     at Generator.next (<anonymous>)
>     at /<projectPath>/node_modules/tslib/tslib.js:167:75
>     at new Promise (<anonymous>)
>     at Object.__awaiter (/<projectPath>/node_modules/tslib/tslib.js:163:16)
>     at authentication (/<projectPath>/node_modules/@commercelayer/js-auth/lib/cjs/index.js:1:377)
>     at CommerceSource.<anonymous> (/<projectPath>/src/commerce-source.ts:24:36)
>     at step (/<projectPath>/src/commerce-source.ts:33:23)
>     at Object.next (/<projectPath>/src/commerce-source.ts:14:53)
>     at /<projectPath>/src/commerce-source.ts:8:71

Basic singleton wrapper:

```
export class CommerceSource {

    private accessToken: TBaseReturn;
    private clayer: CommerceLayerClient;

    private static _singleton: CommerceSource;
    public static async initialize(){
        this._singleton = new CommerceSource();

        this._singleton.accessToken = await this._singleton.getAccessCredentials();
        this._singleton.clayer = CommerceLayer({
            organization: '<my-app>',
            accessToken: this._singleton.accessToken.accessToken
        })
    }

    public static getInstance(): CommerceSource { return this._singleton }

    private async getAccessCredentials():Promise<TBaseReturn>{
        return authentication('client_credentials', {
            clientId: '<myClientID>',
            clientSecret: '<myClientSecret>',
            slug: '<my-app>',
          })
    }
}
```

The error occurs when the singleton's getAccessCredentials function is called.

**To Reproduce**
1. Setup a blank project. NPM install js-auth & CL SDK.
2. Attempt to initialize.

**Expected behavior**
Should initialize and dependencies should be installed.

**Desktop (please complete the following information):**

- OS: CentOS 7

**Comment by franciscarriere** [comment]
I was able to resolve the issue. The problem is because NodeJS 16 does not have a global "fetch" function, which was added in NodeJS v18.

To resolve:

npm install node-fetch

and in your index.ts / app.ts, add 

import fetch from 'node-fetch'
globalThis.fetch = fetch
